@startuml
package helper{
annotation helper {


-getPort(): *string
-getIssuer(): *string
-getPeriod(): *uint
-getIDSeed(): *uint64
-getMaxSize(): *int64
+ReadEnv(): *string, *uint64, *string, *uint, *int64
+CreateDirectory(folder string): error
+FilenameWithoutExtension(filename string): string
+ReadFileNamesOfDirectory(folder *string): []string
+MapUserID(id *string)
}
}
package http-api/common{
annotation http-api/common {


-extractCredentials(request *Request): *string, *string
-extractFileName(request *Request): *string
+ChallengeLoginHTTP(request *Request, writer ResponseWriter): *UserOtp, error
+ChallengeReadFileHTTP(request *Request, writer ResponseWriter): *[]byte, error
+ChallengeWriteFileHTTP(request *Request, writer ResponseWriter, maxSize *int64): error
+SanitizeFileName(fileName *string)
+SanitizeUploadFile(request *Request, maxSize *int64): string, string, File, *FileHeader, error
}
}
package http-api/responder/otp-identity-responder{
annotation http-api/responder/otp-identity-responder {
-const Url: IdentityResponse
-const Combination: IdentityResponse
-const QR: IdentityResponse

+SelectResponder(mode *IdentityResponse, newUser *UserOtp, w *ResponseWriter): IdentityResponder
}
interface IdentityResponder{
+Send()
}
class CombinedResponder {
+Tool: IdentityResponderTool
+Send()
}
class CombinedTemplate {
+OtpUrl: URL
+Image: string

}
class QRCodeResponder {
+Tool: IdentityResponderTool
+Send()
}
class IdentityResponderTool {
+NewUser: *UserOtp
+HttpResponder: *ResponseWriter

}
class UrlResponder {
+Tool: IdentityResponderTool
+Send()
}
}
package http-api/responder/otp-login-responder{
annotation http-api/responder/otp-login-responder {
-const AccountInterface: LoginResponse
-const FileList: LoginResponse

+SelectResponder(mode *LoginResponse, foundID *UserOtp, w *ResponseWriter): LoginResponder
}
interface LoginResponder{
+Send()
}
class AccountInterfaceResponder {
+Tool: LoginResponderTool
+Send()
}
class AccountInterfaceTemplate {
+UserID: string
+Files: []string

}
class FileListResponder {
+Tool: LoginResponderTool
+Send()
}
class FileListTemplate {
+UserID: string

}
class LoginResponderTool {
+User: *UserOtp
+Files: []string
+HttpResponder: *ResponseWriter

}
}
package http-api{
annotation http-api {


+FileHandler(maxSize *int64)
+MiscHandler()
+OTPHandler()
+InitializeHTTPServer(port *string, maxSize *int64)
}
}
package permission-controller/id-manager/content-modifier{
annotation permission-controller/id-manager/content-modifier {

-var PathToIdentities: 
-var PathToFilesOfIdentities: 
+WriteFile(fileName string, file *File): error
+ReadFile(name string): *[]byte, error
+DeleteFile()
+InitializeOTPModifier()
+ReadAllIdentities(): *map[string]*UserOtp
+ReadIdentity(id *string): *UserOtp, error
+WriteIdentity(id *string, identity *UserOtp): error
+DeleteIdentity(id *string): error
+ReadFilesOfIdentity(id *string): []string
}
class UserOtp {
+Id: string
+Key: Key

}
class FilesystemUserOtp {
+URL_Key: string
+Issued_Date: string

}
class LoginChallenge {
+Files: []string

}
}
package permission-controller/id-manager{
annotation permission-controller/id-manager {

-var existingIDs: map[string]*UserOtp
+InitializeIDManager()
+ExistsIdentity(id *string): *UserOtp, error
+CreateIdentity(id *string, user_otp *UserOtp): error
+ReadFilesOfIdentity(id *string): []string
}
}
package permission-controller{
annotation permission-controller {
-const SAFE_CHARACTERS: STRING
-var idGenerator: *Shortid
-var GenerateOtpOpts: GenerateOpts
-var ValidateOtpOpts: ValidateOpts
+ChallengeLogin(id *string, clientCode *string, time *Time): *UserOtp, error
+ChallengeReadFile(id *string, clientCode *string, time *Time, fileName *string): *[]byte, error
+ChallengeWriteFile(id *string, clientCode *string, time *Time, fileName *string, file *File): error
+ChallengeDeleteFile()
+ChallengeDeleteIdentity()
+InitializeOTPGenerator(seed *uint64, issuer *string, period *uint)
+CreateIdentity(): *UserOtp, error
}
}
package .{
annotation . {


-main()
}
}
"CombinedResponder" --> "IdentityResponderTool"
"QRCodeResponder" --> "IdentityResponderTool"
"UrlResponder" --> "IdentityResponderTool"
"IdentityResponderTool" --> "UserOtp"
"AccountInterfaceResponder" --> "LoginResponderTool"
"FileListResponder" --> "LoginResponderTool"
"LoginResponderTool" --> "UserOtp"
"CombinedResponder" --|> "IdentityResponder"
"CombinedResponder" --|> "LoginResponder"
"QRCodeResponder" --|> "IdentityResponder"
"QRCodeResponder" --|> "LoginResponder"
"UrlResponder" --|> "IdentityResponder"
"UrlResponder" --|> "LoginResponder"
"AccountInterfaceResponder" --|> "IdentityResponder"
"AccountInterfaceResponder" --|> "LoginResponder"
"FileListResponder" --|> "IdentityResponder"
"FileListResponder" --|> "LoginResponder"
@enduml