@startuml
package content-modifier{
annotation content-modifier {


+WriteFile()
+ReadFile()
+DeleteFile()
+ReadIdentity()
+WriteIdentity()
+DeleteIdentity()
}
}
package http-api{
annotation http-api {


+InitializeHTTPServer(port *string)
}
}
package permission-controller{
annotation permission-controller {


+ChallengeReadFile()
+ChallengeWriteFile()
+ChallengeDeleteFile()
+ChallengeDeleteIdentity()
+CreateIdentity()
}
}
package .{
annotation . {


-main()
-readEnv(): *string
}
}


@enduml