@startuml
package content-modifier{
annotation content-modifier {


+WriteFile()
+ReadFile()
+DeleteFile()
+ReadIdentity()
+WriteIdentity(identity *User_otp): error
+DeleteIdentity()
}
class User_otp {
+Id: string
+Key: Key

}
}
package helper{
annotation helper {


-getPort(): *string
-getIssuer(): *string
-getPeriod(): *uint
-getIDSeed(): *uint64
+ReadEnv(): *string, *uint64, *string, *uint
}
}
package http-api{
annotation http-api {


+OTPHandler()
+InitializeHTTPServer(port *string)
}
}
package permission-controller{
annotation permission-controller {

-var id_generator: *Shortid
-var otp_opts: GenerateOpts
+ChallengeReadFile()
+ChallengeWriteFile()
+ChallengeDeleteFile()
+ChallengeDeleteIdentity()
+InitializeOTPGenerator(seed *uint64, issuer *string, period *uint)
+CreateIdentity(): *User_otp, error
}
}
package .{
annotation . {


-main()
}
}


@enduml