@startuml
package otpfilemanager as "otp-filemanager" {

package otp {
class otpaccessmanager as "otp-access-manager" {
}

class otpinitializer as "otp-initializer" {
}

}

package filesystemmanager as "filesystem-manager" {

class filemodifier as "file-modifier" {
}

class otpmodifier as "otp-modifier" {
}

}

class httpapi as "http-api" {
}

}

httpapi --> otpinitializer: create identity
httpapi --> otpaccessmanager: create files/read files
otpaccessmanager --> otpmodifier: read/delete identity 
otpaccessmanager --> filemodifier: read/create/delete file
otpinitializer --> otpmodifier: create identity

@enduml
